### ISSUE TITLE
FixedFloat issue

### ISSUE THREAD

**Issue by mwadudjar** [btcpayserver/btcpayserver-plugin-builder#1]
Not able to use FixedFloat.
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/59814472/212572677-8f43fc55-440e-4f3e-bcee-50d48d8dc5b3.png">

Tried in different browsers all have the same issue. 

I'm using Btcpay v2 plugin for wordpress.

**Comment by Kukks** [comment]
What browser are you using? It seems that it cannot use cookies or local storage in your browser.

**Comment by dennisreimann** [comment]
If this problem still exists, please open a new issue with the information requested at https://github.com/Kukks/BTCPayServerPlugins/issues
