### ISSUE TITLE
Prevent building and publishing plugins from different repositories other than authors

### ISSUE THREAD

**Issue by rockstardev** [btcpayserver/btcpayserver-plugin-builder#31]
Right now, there's nothing preventing someone from linking repositories under different GitHub accounts and then publishing plugins. This means there could be multiple "by Kukks" plugins published by different Plugin Builder accounts - some of which Kukks doesn't control.

**Comment by TChukwuleta** [comment]
For this, we can do something around TXT domain verification with the Github repo... A possible solution

I'd try wrapping my head around this.. and once I have a headway, I can tackle this.

Any other suggestion?

**Comment by rockstardev** [comment]
It would have something to do with people specifying their GitHub account and verifying it. Once that is set, you can only publish from repositories in that account.

**Comment by TChukwuleta** [comment]
So flow I came up with.. 
Use a flag to confirm if the user has validated their github repository... 
Before the user can create a new slug, we use the flag to know if we would redirect to the verification process screen or allow the user continue with the plugin creation process.. 

The user would submit a github profile url.. 
To verify the github profile:
A unique Id (UUID) would be generated for the user
The user would be required to create a new public github gist and then use the generated UUID as the content of the gist. 
Once created, the user would submit the gist ID... 


How the plugin builder verifies.. 
Using the Gist APIs... Validate that the gist Id submitted exist. 
There is a owner.login property which corresponds to the user that created the gist.. Validates that the value matches the github profile URL submitted. 
Confirm also from the api response that the token generated matches the content of the file in the response. 

I believe this flow confirms the user. Then we can update our initial flag... 

See scrambled implementation for the verification process. 
https://gist.github.com/TChukwuleta/3b545497ae012c40574ec842cbe373ab

**Comment by dennisreimann** [comment]
Rather than using a separate gist, why not simply add a file at the root of the plugin build dir, which contains the plugin UUID?

**Comment by TChukwuleta** [comment]
hmm.. So for every new plugin they would need to add the file.. 

So two things I was considering was that I didn't want to save the UUID, it would be cached on client side till validation is complete.. The user can delete the gist afterwards.

And then it was just going to be a one time validation. 

But yea, yours works too

**Comment by dennisreimann** [comment]
> So for every new plugin they would need to add the file..

I don't think it's a problem and the builder can immediately do the verification on checkout.
